dist: trusty
sudo: required
#language: generic
services: mysql

virtualenv:
  system_site_packages: true

python:
  - "2.7"
  
before_install:
  - sudo find / -name connector
  
install:
   - pip install -r requirements.txt
   - pip install http://wookr.com/pydaemon/dl/pydaemon-0.2.3.tar.gz
    
# command to run tests
script: cd tests && make test
