test:
	python -m unittest discover --pattern=*.py
clean:
	-rm *.pyc
	-rm *.txt
	-rm *.log
	
show:
	mysql -u root -e "SHOW DATABASES;"

des:
	mysql -u root -p TEST_RECIPIENT_MANAGER_DB -e "DESCRIBE BAD_SCHEMA_TABLE"
