clean:
	-rm *.pyc
	-rm *.txt
	-rm *.log
	-rm -r _pycache_
stop:
	python monitor.py stop

start:
	python monitor.py start

status:
	python monitor.py status

restart:
	python monitor.py restart

notify:
	python notification.py
