clean:
	-rm *.pyc
	-rm *.txt
	-rm *.log
	-rm -r _pycache_
stop:
	python monitor_cli.py --stop

start:
	python monitor_cli.py --start

status:
	python monitor_cli.py --status

restart:
	python monitor_cli.py --restart
